query getCarPurchaseCostProvinceById($provinceId: String!) {
	getCarPurchaseCostProvinceById(provinceId: $provinceId) {
		bodyInsuranceOneYear
		civilInsurance
		createdAt
		id
		isActive
		licensePlateFee
		otherCost
		proviceDetail {
			code
			countryCode
			id
			isActive
			name
			slug
		}
		provinceId
		registrationFeeNewCar
		registrationFeeOldCar
		registry
		roadMaintenanceFee
		updatedAt
	}
}
