query getListQuestionByGroup($input: DetailInput!) {
	getListQuestionByGroup(input: $input) {
		answers {
			content
			correctAnswer
			id
			no
			parentNo
			questionId
		}
		answerType
		content
		explainAnswer
		id
		imageExplainAnswer
		images
		isActive
		no
		type
	}
}
